from dataclasses import dataclass
from typing import List

from marshmallow import Schema, fields, post_load

from openfabric_pysdk.utility import SchemaUtil


################################################################
# Config concept class - AUTOGENERATED
################################################################
@dataclass
class ConfigClass:
    app_ids: List[str] = None


################################################################
# ConfigSchema concept class - AUTOGENERATED
################################################################
class ConfigClassSchema(Schema):
    app_ids = fields.List(fields.String())

    @post_load
    def create(self, data, **kwargs):
        return SchemaUtil.create(ConfigClass(), data)
